### ISSUE TITLE
Definir linguagem padrão de commit

### ISSUE THREAD

**Issue by DaviAntonio** [ResidenciaTICBrisa/03_Robotica#14]
O repositório tem commits em português e inglês.
Acredito ser necessário manter um padrão, até porque a mensagem de commit também ajuda a documentar o desenvolvimento do projeto.

**Comment by daniel-de-sousa** [comment]
Para melhor entendimento, acredito que deixar todos os comits de forma simples, no imperativo e em português seja uma boa solução.

Como sugestão, é possível criar um guia de commits com palavras chave, o que facilitará já de cara saber sobre o que se trata determinado commit.

**Comment by DaviAntonio** [comment]
Acho que já podemos oficializar como português.

**Comment by daniel-de-sousa** [comment]
De acordo

**Comment by DaviAntonio** [comment]
As mensagens dos commits serão em português.
