### ISSUE TITLE
Preparar apresentação para primeira entrega

### ISSUE THREAD

**Issue by DaviAntonio** [ResidenciaTICBrisa/03_Robotica#15]
O evento de primeira entrega do projeto será no dia 16/08/2023 (2023-08-16).

## Critérios de aceitação
- [x] a apresentação deve durar **até 5 minutos**
- [x] a apresentação deve abordar
    - [x] relato de experiência
        - [x] contexto
        - [x] desafios
        - [x] solução proposta
    - [x] resultados
        - [x] tecnologias escolhidas e justificativa
        - [x] produtos entregáveis (funcionalidades)
    - [x] roadmap dos próximos 3 meses

**Comment by mrodrigues14** [comment]
Roadmap feito no próprio Projects
