### ISSUE TITLE
Definir linguagem padrão para documentação

### ISSUE THREAD

**Issue by DaviAntonio** [ResidenciaTICBrisa/03_Robotica#19]
O projeto contém documentação em inglês e português. Acredito que a padronização da linguagem da documentação seja necessária para garantir a boa comunicação entre os membros do grupo e entre as partes interessadas no projeto.

Para facilitar a discussão, sugiro as seguintes opções de padrões de linguagens para documentação:
- documentação somente em língua portuguesa
    - toda a documentação não existente será escrita e publicada em língua portuguesa
    - qualquer documentação já existente fora do padrão será traduzida e publicada em português
- documentação somente em língua inglesa
    - toda a documentação não existente será escrita e publicada em língua inglesa
    - qualquer documentação já existente fora do padrão será traduzida e publicada em inglês
- documentação prioritariamente em português
    - toda a documentação não existente será obrigatoriamente escrita e publicada em língua portuguesa
    - opcionalmente, a documentação poderá ser traduzida para o inglês e publicada nesta língua
    - toda a documentação existente somente em inglês será traduzida para o português e publicada em português e em inglês

**Comment by daniel-de-sousa** [comment]
Sou a favor da adoção da terceira opção.
Uma vez que o tema que estamos usando na pages possui suporte para mais um idioma possibilitando que a pessoa altere entre as documentações em português e as documentações em inglês.
Essa funcionalidade pode ser encontrada nesse link [Changing the Language](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/)

**Comment by DaviAntonio** [comment]
Dada a manifestação do grupo e as nossas conversas com a UnBeatables, a equipe optou pela terceira proposta:
- documentação prioritariamente em português
    - toda a documentação não existente será obrigatoriamente escrita e publicada em língua portuguesa
    - opcionalmente, a documentação poderá ser traduzida para o inglês e publicada nesta língua
    - toda a documentação existente somente em inglês será traduzida para o português e publicada em português e em inglês
