### ISSUE TITLE
Realizar demo de Simulação do NAO no Coreograph

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#20]
**Realizar simulação do NAO**

Realizar movimentos basicos e de interesse futuro;
Criação de código, se necessário, para isso.

**Comment by DaviAntonio** [comment]
Os códigos em C++ podem ser testados no NAO virtual do Choregraphe.
Acredito que esse *issue* já possa ser fechado.

**Comment by Gustavo-Macedo1** [comment]
Foram conduzidas simulações extensivas no Choregraphe usando o NAO v4 no laboratório. Sendo assim, a issue será fechada.
