### ISSUE TITLE
Criação do Hello World NAO C++

### ISSUE THREAD

**Issue by Gustavo-Macedo1** [ResidenciaTICBrisa/03_Robotica#22]
O Hello World deve ser feito em linguagem clara e objetiva, de forma que capacite (no viés de iniciação) qualquer usuário leigo na programação do robô NAO em C++, fazendo uso das SDKs.

**Objetivos necessários para fechar essa issue:**

- [ ] Estudo sobre o uso da NAOqi SDK C++
- [ ] Criação de documentação de uso básico do NAOqi SDK C++

**Comment by mrodrigues14** [comment]
Código base para o Hello world na SDK C++ consiste em seguir alguns padrões necessários para compilação do mesmo. Será adicionado parâmetros necessários e ações necessárias para tal tarefa

**Comment by DaviAntonio** [comment]
Eu consegui criar um código com o Hello World do NAO usando os métodos recomendados para a SDK 2.1 e 2.8.
Há também um que usa os métodos legados da 1.4, que ainda funcionam na 2.1, mas geram vários avisos.
Há alguma *branch* em que eu possa realizar o *commit*?

**Comment by DaviAntonio** [comment]
Consegui um Hello World usando módulos.
Não há como criar um módulo lançado pelo qicli porque o NAOqi 2.1 não possui todos os recursos do NAOqi 2.8.
Com a abordagem que usei o módulo é feito usando os recursos do NAOqi 2 que facilitam a criação, apesar da maneira clássica feita no NAOqi 1 ainda ser usável e não emitir avisos.
Quando houver uma *branch* disponível eu já disponibilizo os três códigos.

**Comment by DaviAntonio** [comment]
Consegui o Hello World dos módulos.
ele é o mais importante, pois a interação com a ALMemory e os eventos depende de serializarmos a classe e publicá-la no broker como um módulo.

**Comment by DaviAntonio** [comment]
Concluído Hello World de um módulo que executa as rotinas de movimento WakeUp e Rest com uso de eventos.

**Comment by DaviAntonio** [comment]
Concluído Hello World das funções de caminhada do NAO. O teste foi feito apenas na simulação de baixa fidelidade do Choregraphe.
