### ISSUE TITLE
Documentação de instalação do OpenCV

### ISSUE THREAD

**Issue by Gustavo-Macedo1** [ResidenciaTICBrisa/03_Robotica#23]
Para prosseguir com a demo e contribuir com o UnBeatables, é necessário um tutorial de instalação do OpenCV para que o usuário consiga utilizar recursos de visão computacional.

**Para fechar essa issue, é necessário:**

- [ ] Documentação de download e instalação do OpenCV no sistema operacional adequado à criação das demos.

**Comment by daniel-de-sousa** [comment]
Diante a pesquisas e processos de instalação, foi feito a descoberta de que o SDK do C++ já possui o OpenCV com ele, então na realização da instalação por fora, no sistema operacional usado, é necessário que se exclua ele da pasta do SDK.

O que leva a testar a seguinte hipótese:
Sera que é realmente necessário que se instale o OpenCV no sistema utilizado ou é possível se utilizar do que já esta no SDK para poder fazer toda a programação desejada?

**Comment by daniel-de-sousa** [comment]
Uma vez que foi decidido utilizar do OpenCV que está dentro do NAOqi, essa issue e sua complementar serão fechadas.
