### ISSUE TITLE
Arrumar a cópia do golden pendrive

### ISSUE THREAD

**Issue by Gustavo-Macedo1** [ResidenciaTICBrisa/03_Robotica#24]
Para a operação do NAO v4 por parte do UnBeatables, precisamos salvar o conteúdo de um pen-drive único que contém o sistema necessário para usar o NAO v4, uma vez que este está inacessível nas fontes oficiais de distribuição atualmente. O pen-drive apresenta problemas de compartilhamento.

**Para fechar essa issue, será necessário:**

- [x] Ter acesso ao pen-drive
- [x] Analisar o pen-drive
- [x] Fazer teste de cópia e transferência de arquivos
- [x] Realizar o diagnóstico
- [x] Encontrar solução para o problema de compartilhamento do pen-drive
- [x] Desenvolver uma cópia de demonstração

**Comment by DaviAntonio** [comment]
Pela documentação da Aldebaran/Softbanks o pendrive é criado usando-se o NAO Flasher e uma imagem do sistema operacional do robô.
Encontrei um [site](https://www.robotlab.com/support/factory-reset-nao-robot-flasher) com várias versões do sistema operacional, sendo que há duas para o NAOv6:
- [V4 NAO](https://www.robotlab.com/hubfs/Choregraphe_Files/opennao-atom-system-image-2.1.4.13_2015-08-27.opn)
- [V5 NAO](https://www.robotlab.com/hubfs/Choregraphe_Files/opennao-atom-system-image-2.1.4.13_2015-08-27.opn)
- [V6 NAO 2.8.6](https://www.robotlab.com/hubfs/nao-x86-2.8.6.23_20191127_221232.opn)
- [V6 NAO 2.8.7](https://www.robotlab.com/hubfs/2.8.7.4_20210820_094013.opn)

**Comment by DaviAntonio** [comment]
Hash SHA256 dos arquivos nos diretórios:
```
5d18427ba6f5199d30cf29941b20ad5fa6a06b8f64a29126953cdfa33dbb9a24  ./V4 NAO (Orange or Light Blue color robot)/opennao-atom-system-image-2.1.4.13_2015-08-27.opn
de81710913c701cc3763662ab3be9ad5a11f6541af203bce201e0798d82b69b2  ./V6 NAO 2.8.6 (Dark Gray color robot)/nao-x86-2.8.6.23_20191127_221232.opn
5d18427ba6f5199d30cf29941b20ad5fa6a06b8f64a29126953cdfa33dbb9a24  ./V5 NAO (Red or Blue color robot)/opennao-atom-system-image-2.1.4.13_2015-08-27.opn
d82e5dd221712555f20c430f3ebcbe46825d5179f1bc0e2594629489855e24a4  ./V6 NAO 2.8.7 (Dark Gray color robot)/2.8.7.4_20210820_094013.opn
```

**Comment by DaviAntonio** [comment]
Hash SHA256 dos arquivos:

```
5d18427ba6f5199d30cf29941b20ad5fa6a06b8f64a29126953cdfa33dbb9a24  ./opennao-atom-system-image-2.1.4.13_2015-08-27.opn
de81710913c701cc3763662ab3be9ad5a11f6541af203bce201e0798d82b69b2  ./nao-x86-2.8.6.23_20191127_221232.opn
5d18427ba6f5199d30cf29941b20ad5fa6a06b8f64a29126953cdfa33dbb9a24  ./opennao-atom-system-image-2.1.4.13_2015-08-27.opn
d82e5dd221712555f20c430f3ebcbe46825d5179f1bc0e2594629489855e24a4  ./2.8.7.4_20210820_094013.opn
```

**Comment by DaviAntonio** [comment]
Verificou-se que os pendrives gerados pelo NAO Flasher são ilegíveis, pois usam um esquema de partição próprio. Os pendrives fornecidos pela UnBeatles encontram-se na mesma situação.

**Comment by DaviAntonio** [comment]
Realizou-se o backup dos pendrives da UnBeatles usando-se a ferramenta `dd` no GNU/Linux. No caso do pendrive ser identificado como o dispositivo `/dev/sda`:
`dd if=/dev/sda of=backup-drive status=progress bs=4M conv=fsync`

**Comment by DaviAntonio** [comment]
Os pendrives dependem dos arquivos `.opn` fornecidos pela Aldebaran/Softbanks. Cada versão do NAO possui seu próprio arquivo, e apenas o do NAOv6 está atualmente disponível.

**Comment by DaviAntonio** [comment]
Dependendo do NAOv4 que ficar no laboratório, teremos a autorização para apagar as configurações.
Vamos gerar o pendrive na VM usando a `opn` que temos e tentar fazer o reset do NAO com ele.

**Comment by DaviAntonio** [comment]
Um dos NAOv4 foi restaurado com sucesso usando o firmware gerado a partir da imagem `opennao-atom-system-image-2.1.4.13_2015-08-27.opn` com hash SHA256 `5d18427ba6f5199d30cf29941b20ad5fa6a06b8f64a29126953cdfa33dbb9a24`.

**Comment by DaviAntonio** [comment]
Em relação ao problema de compartilhamento, sugiro que a equipe permaneça com o pendrive atual, e gerem novos pendrives a partir da VM e o arquivo fornecido.

**Comment by DaviAntonio** [comment]
Foi gerada um pendrive de restauração comum, não a completa, a partir da imagem OPN do NAOv4 referida anteriormente. A equipe observou o processo de reset.
Recomendo aumentar o volume da fala do NAO nas próximas demonstrações, pois ele fala algumas frases no processo.

**Comment by Gustavo-Macedo1** [comment]
Como todos os processos foram cumpridos, podemos fechar essa issue.
