### ISSUE TITLE
Lançamento semanal de atualizações na Git Page

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#29]
# Atualizações semanais da Git Page

As atualizações semanais serão feitas na Git Page no grupo com o intuito de melhor comunicação com o cliente.

**Comment by DaviAntonio** [comment]
Esse procedimento é inviável e as partes interessadas preferem que o progresso seja registrado nas issues.
Acho que podemos fechar como `wontfix`.

**Comment by daniel-de-sousa** [comment]
Concordo, uma vez que essa issue foi aberta no começo do projeto como uma ideia inicial que não foi para frente.
