### ISSUE TITLE
Estudos de ferramentas de visão computacional

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#30]
# Estudos de tecnologias de Visão Computacional 

Esse estudo tem como objetivo capacitar os membros a estarem realizando a criação de códigos de visão computacional para serem utilizados no projeto

**Comment by DaviAntonio** [comment]
As interfaces disponibilizadas para reconhecimento visual estão documentadas no módulo [NAOqi Vision](http://doc.aldebaran.com/2-1/naoqi/vision/index.html).
Para o nosso projeto recomenda-se o uso dos métodos que publicam eventos compatíveis com o módulo `ALTracker`, possibilitando a movimentação automática em direção a um alvo, com a possibilidade de se especificar uma distância limite.
O robô possui acesso a API do OpenCV, mas não há feedback gráfico normalmente usado na versão desktop, dificultando o desenvolvimento.
