### ISSUE TITLE
Testes de Visão Computacional em ambiente de simulação virtual

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#32]
# Testes Virtuais

Devido a necessidade de averiguar se os códigos estão funcionando da maneira esperada, há a necessidade da realização de testes em ambiente virtual. 

Deverá ser utilizado o ambiente de teste que a equipe Unbeatables já utiliza, tendo em vista sua experiência com o mesmo.

**Comment by daniel-de-sousa** [comment]
Como não existe ambiente virtual para o NAO, em vez de se testar em um ambiente virtual, a Issue será mudada apenas para teste de visão computacional.

**Comment by daniel-de-sousa** [comment]
Visto que o novo design da git pages foi finalizado, essa Issue será momentaneamente pausada para que se possa trabalhar na refatoração da git pages. Logo após ser concluída, se a Issue ainda estiver ativa, será voltada a atenção para suas atividades.

**Comment by DaviAntonio** [comment]
Eu consegui compilar o exemplo de simulação do NAOv4, mas ele supõe que o desenvolvedor escreverá um simulador e fornecerá os dados inerciais, de imagem e de posição do robô para o módulo HAL.
Isso é um grande problema, pois o exemplo de simulação já apresenta diversos problemas quando executado no Choregraphe, pois ele não fornece esses valores.
A outra solução que tentei foi o webots, uma ferramenta também mencionada na documentação do NAOv4, mas encontrei ainda mais problemas. O webots 8, indicado na documentação, não pode mais ser ativado. A versão 2019a, a primeira a ser lançada como código aberto, não é compatível com o Ubuntu 14 e também não consegue ser compilada, pois os desenvolvedores criaram uma versão especial do QT, mas não mais a fornecem.

**Comment by DaviAntonio** [comment]
Os códigos de movimento foram simulados no simulador de baixa fidelidade do Choregraphe.
A visão computacional não pode ser simulada por lá, apenas no webots ou criando o seu próprio simulador usando o SDK que parou de ser suportado no NAOv4.

**Comment by Gustavo-Macedo1** [comment]
Os testes de visão computacional foram realizados em laboratório, porém sem sucesso para demonstrações. O robô apresenta limitações e bugs no que se refere à interação com os objetos identificados com visão computacional. 

Sendo assim, podemos fechar essa issue.
