### ISSUE TITLE
Testar demo em robo real e documentar o processo

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#34]
# Teste da demo criada em robô real

A partir da demo criada será conectado ao robô escolhido, V4 ou V6 e será realizado um teste da demo.

Necessário documentar todo o processo

**Comment by Gustavo-Macedo1** [comment]
A demo foi testada em robô real, o Hello World foi criado e documentado.

Sendo assim, podemos fechar essa issue.
