### ISSUE TITLE
Documentação do ambiente de simulação virtual

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#35]
Documentar todo passo a passo de como poderá ser feito a simulação virtual dos códigos

**Comment by daniel-de-sousa** [comment]
Ao que parece não existe um ambiente de simulação virtual, para testes e debug é usado as ferramentas que já foram introduzidas através dos tutoriais e a compilaçlão do código no próprio NAO, por isso, essa Issue acaba por se tornar dispensável.
