### ISSUE TITLE
Criação de guia de boas praticas Unbeatables

### ISSUE THREAD

**Issue by mrodrigues14** [ResidenciaTICBrisa/03_Robotica#37]
# Confecção de guia de boas práticas do projeto

Devido a diversidade de instalações necessárias e tecnologias a serem utilizadas será criado um guia de boas práticas para melhor instrução de futuros estudantes que irão integrar a equipe Unbeatables.

No guia deverá constar todo os tutoriais e documentações utilizadas durante o projeto, gerando assim um documento que possa ser utilizado para os futuros integrantes da equipe, gerando mais tempo para o desenvolvimento de novas funcionalidades para os futuros projetos da equipe.

**Comment by Gustavo-Macedo1** [comment]
Como esse era um recurso extra e ficamos sem tempo, optamos pela não confecção do mesmo ao dar prioridade para outros assuntos. Assim, fecharemos como won't fix.
