### ISSUE TITLE
Tutorial da Instalação do NAOqi 2.1(E suas dependências)

### ISSUE THREAD

**Issue by daniel-de-sousa** [ResidenciaTICBrisa/03_Robotica#5]
## NAO
Existe mais de uma versão de NAO disponível, sendo que para isso, o software utilização para realizar a comunicação com o NAO apresenta também versões diferentes para cada versão de NAO.

## Objetivo
O objetivo é mediante uma máquina virtual, documentar o processo de instalação do software na versão necessária para a comunicação do NAOqi 2.1 que irá ser utilizado para se comunicar com o NAO V4

## Critérios de Aceitação
- [ ] Tutorial em MD com o passo a passo como instalar a versão apresentada juntamente com um teste de Hello World para verificar se foi instalada corretamente.

**Comment by daniel-de-sousa** [comment]
Há alguns problemas com relação a transferência de arquivos do computador para a VM, como também com o acesso ao site da aldebaran dentro da vm, apresentando o seguinte erro:
"Secure Connection Failed"

Interromperei minimamente a instalação para solucionar algum desses problemas a fim de conseguir fazer o download do arquivo necessário para instalar o SDK

**Comment by daniel-de-sousa** [comment]
> Há alguns problemas com relação ao download de arquivos do computador para a VM, como também com o acesso ao site da aldebaran dentro da vm, apresentando o seguinte erro: " Secure Connection Failed"
> 
> Interromperei minimamente a instalação para solucionar alguns desses problemas a fim de conseguir fazer o download do arquivo necessário para instalar o SDK

O erro foi parcialmente corrigido, foi feito uma tentativa de instalar outros navegadores mas sem sucesso, até mesmo pelo terminal, a solução encontrada foi compartilhar uma pasta do sistema com a maquina virtual, porém so é possível acessar seu conteúdo via linha de terminal com o usuário rooot.

**Comment by daniel-de-sousa** [comment]
> > Há alguns problemas com relação ao download de arquivos do computador para a VM, como também com o acesso ao site da aldebaran dentro da vm, apresentando o seguinte erro: " Secure Connection Failed"
> > Interromperei minimamente a instalação para solucionar alguns desses problemas a fim de conseguir fazer o download do arquivo necessário para instalar o SDK
> 
> O erro foi parcialmente corrigido, foi feito uma tentativa de instalar outros navegadores mas sem sucesso, até mesmo pelo terminal, a solução encontrada foi compartilhar uma pasta do sistema com a maquina virtual, porém so é possível acessar seu conteúdo via linha de terminal com o usuário rooot.

Apos alguns testes foi possível visualizar o conteúdo dentro da maquina virtual, porém é incapaz de se instalar o conteúdo, sendo necessário alguma outra forma de solução

**Comment by daniel-de-sousa** [comment]
Soluções tentadas que deram falhas:

Modificação do SSL o navegador firefox
Download de outros navegadores
Pasta compartilhada com a maquina primaria
Transferência de arquivos.

Próxima possível solução a ser tentada.
Foi criado um drive com os arquivos que se desejava instalar, porém o navegador do firefox no Ubuntu 12.04 é antigo, e não suporta acessar o drive, por isso, em vez de tentar solucionar o problema de acessar o site da aldebaran, será feito a tentativa de acessar o drive para poder baixar os arquivos, um possibilidade é colocar no mega ou talvez outro armazenamento em nuvem.

**Comment by DaviAntonio** [comment]
Há uma maneira de se contornar a maioria dos problemas.
Fui anotando aqui cada um e procurando a solução. No fim, para fazer com que o `naoqi 2.1` seja instalado na VM do Ubuntu 12.04, é necessário:
- corrigir o `sources.list`, apontando para as últimas atualizações que foram disponibilizadas para o Ubuntu 12
- atualizar o sistema, lembrando que nessa versão há apenas `apt-get`
- compilar uma nova versão do Python 2.7, pois a versão atual não tem suporte completo ao SSL
- instalar uma versão nova do `pip`, pois a incluída é extremamente antiga

Já tenho uma versão funcionando localmente, mas é necessário documentar o processo e passar o possível para scripts de modo a facilitar a experiência de usuário

**Comment by daniel-de-sousa** [comment]
Diante de problemas tanto em questão da Maquina virtual quanto em questão das dependências a serem instaladas, e até mesmo o perigo de futuramente os scripts pararem de funcionar devido a uma atualização nos repositórios usados, foi se adotado uma nova frente a fim de tentar solucionar o problema.

No presente momento foi consegui fazer o SDK do C++ rodar na VM do Ubuntu 16.
A partir disso os novos esforços vão ser concentrados em fazer todas os softwares necessários para o NAOqi V4 funcionar nessa VM, uma vez isso irá facilitar sua utilização, alem de descartar a utilização de uma ISO e de alguns scripts.

**Comment by Gustavo-Macedo1** [comment]
A instalação foi realizada com sucesso no Ubuntu 16.04. A documentação também foi criada e está disponível na Git page.
