### ISSUE TITLE
Usar épicos (milestones)

### ISSUE THREAD

**Issue by DaviAntonio** [ResidenciaTICBrisa/03_Robotica#51]
Investigar o uso do recurso de épicos (milestones):
- para atribuir as issues às sprints
- para marcar as funcionalidades de alto nível
    - configuração de ambiente EMA
    - configuração de ambiente UnBeatables
    - elaborar Hello World EMA
    - elaborar Hello World UnBeatables
    - demonstração extra com NAO

**Comment by DaviAntonio** [comment]
Não usamos, então acredito que podemos fechar como `wontfix`

**Comment by daniel-de-sousa** [comment]
Apoio, já pode fechar essa issue.
