### ISSUE TITLE
Refatoração da GitPages

### ISSUE THREAD

**Issue by daniel-de-sousa** [ResidenciaTICBrisa/03_Robotica#65]
**Título:** Refatoração da GitPages

**Descrição:** Com o novo design terminado se inicia o processo de refatoração da git pages, mediante a um processo que dessa vez incluirá mais do que apenas usar as ferramentas do mkdocs, podendo ser necessário a sua criação em HTML e CSS puro e depois realizado a tentativa de vinculação ao mkdocs. E caso isso não seja possível, talvez seja necessário passar todas as partes presentes no mkdos para HTML e CSS.

**Comment by DaviAntonio** [comment]
Mudanças sugeridas pelas partes interessadas:
- trocar a cor do cabeçalho para ser igual da imagem
  - identidade visual única: cores e tipografia
- rodapé na página inicia
  - nome da empresa
  - UnB
  - BRISA
- títulos do menu navegação
  - devem ser mais didáticos: o que o usuário precisa fazer primeiro?
- adicionar aba "sobre" com um relato de exp
- adicionar aba contato com informações relevantes para contratação
- não somos desenvolvedores, mas fundadores
- padronizar todas as fontes, por exemplo`* {font-family: 'Roboto';}`no *override* global
- alinhar parágrafos com imagem (diminuir imagem ou alinhar texto)
- ou dark ou normal (escolher um)

**Comment by daniel-de-sousa** [comment]
Status da Pages - A maioria das requisições foram cumpridas, nesse momento o que falta finalizar são as seguintes sugestões:

* Identidade visual nas páginas geradas pelo mkdocs
* Página de contato

**Comment by Gustavo-Macedo1** [comment]
A page está pronta, com a página "Equipe" descrevendo os membros e mostrando formas de contato. Além disso, corrigimos a identidade visual ao respeitarmos a palheta de cores dos menus e efeitos especiais.

Sendo assim, a issue será fechada.
